import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';


@Component({
  selector: 'app-home',
  templateUrl: './home.page.html',
  styleUrls: ['./home.page.scss'],
})
export class HomePage implements OnInit {

  categorias = [
    {cod: 1, nome: 'Burguers'},
    {cod: 2, nome: 'Pizzas'},
    {cod: 3, nome: 'Doces'},
    {cod: 4, nome: 'Bebidas'}
  ]

  produtos = [
    {cod: 1,  nome: 'Hambúrguer Bacon e Cheddar',     categoria: 1,   valor: 21.50, imagem: 'Burguer_1.jpeg', visible: false, descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nunc sem, interdum ut consectetur ut, elementum ac turpis. Sed at ullamcorper massa, in fermentum leo. Aliquam erat volutpat. Integer non velit a ante laoreet elementum. Proin aliquet arcu at quam dapibus, nec laoreet ante vehicula. Donec condimentum accumsan molestie. Vestibulum laoreet posuere neque, sit amet dictum urna fringilla sed. In in ante vitae sapien blandit elementum sit amet ac erat. Nunc semper hendrerit turpis sit amet tempus. Mauris imperdiet mattis feugiat. Ut et erat euismod, finibus enim et, placerat tellus. Mauris laoreet tellus at erat blandit dignissim. Donec id enim at erat imperdiet gravida et eget dui.',}, 
    {cod: 2,  nome: 'Gothan Burger',                  categoria: 1,   valor: 25.35, imagem: 'Burguer_2.jpeg', visible: false, descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nunc sem, interdum ut consectetur ut, elementum ac turpis. Sed at ullamcorper massa, in fermentum leo. Aliquam erat volutpat. Integer non velit a ante laoreet elementum. Proin aliquet arcu at quam dapibus, nec laoreet ante vehicula. Donec condimentum accumsan molestie. Vestibulum laoreet posuere neque, sit amet dictum urna fringilla sed. In in ante vitae sapien blandit elementum sit amet ac erat. Nunc semper hendrerit turpis sit amet tempus. Mauris imperdiet mattis feugiat. Ut et erat euismod, finibus enim et, placerat tellus. Mauris laoreet tellus at erat blandit dignissim. Donec id enim at erat imperdiet gravida et eget dui.',}, 
    {cod: 3,  nome: 'Hambúrguer de Siri',             categoria: 1,   valor: 23.00, imagem: 'Burguer_3.jpeg', visible: false, descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nunc sem, interdum ut consectetur ut, elementum ac turpis. Sed at ullamcorper massa, in fermentum leo. Aliquam erat volutpat. Integer non velit a ante laoreet elementum. Proin aliquet arcu at quam dapibus, nec laoreet ante vehicula. Donec condimentum accumsan molestie. Vestibulum laoreet posuere neque, sit amet dictum urna fringilla sed. In in ante vitae sapien blandit elementum sit amet ac erat. Nunc semper hendrerit turpis sit amet tempus. Mauris imperdiet mattis feugiat. Ut et erat euismod, finibus enim et, placerat tellus. Mauris laoreet tellus at erat blandit dignissim. Donec id enim at erat imperdiet gravida et eget dui.',},
    {cod: 4,  nome: 'Pizza Marguerita',               categoria: 2,   valor: 25.50, imagem: 'Pizza_1.jpeg',   visible: false, descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nunc sem, interdum ut consectetur ut, elementum ac turpis. Sed at ullamcorper massa, in fermentum leo. Aliquam erat volutpat. Integer non velit a ante laoreet elementum. Proin aliquet arcu at quam dapibus, nec laoreet ante vehicula. Donec condimentum accumsan molestie. Vestibulum laoreet posuere neque, sit amet dictum urna fringilla sed. In in ante vitae sapien blandit elementum sit amet ac erat. Nunc semper hendrerit turpis sit amet tempus. Mauris imperdiet mattis feugiat. Ut et erat euismod, finibus enim et, placerat tellus. Mauris laoreet tellus at erat blandit dignissim. Donec id enim at erat imperdiet gravida et eget dui.',},
    {cod: 5,  nome: 'Pizza Napolitana',               categoria: 2,   valor: 22.00, imagem: 'Pizza_2.jpeg',   visible: false, descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nunc sem, interdum ut consectetur ut, elementum ac turpis. Sed at ullamcorper massa, in fermentum leo. Aliquam erat volutpat. Integer non velit a ante laoreet elementum. Proin aliquet arcu at quam dapibus, nec laoreet ante vehicula. Donec condimentum accumsan molestie. Vestibulum laoreet posuere neque, sit amet dictum urna fringilla sed. In in ante vitae sapien blandit elementum sit amet ac erat. Nunc semper hendrerit turpis sit amet tempus. Mauris imperdiet mattis feugiat. Ut et erat euismod, finibus enim et, placerat tellus. Mauris laoreet tellus at erat blandit dignissim. Donec id enim at erat imperdiet gravida et eget dui.',},
    {cod: 6,  nome: 'Pizza Vegetariana',              categoria: 2,   valor: 24.35, imagem: 'Pizza_3.jpeg',   visible: false, descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nunc sem, interdum ut consectetur ut, elementum ac turpis. Sed at ullamcorper massa, in fermentum leo. Aliquam erat volutpat. Integer non velit a ante laoreet elementum. Proin aliquet arcu at quam dapibus, nec laoreet ante vehicula. Donec condimentum accumsan molestie. Vestibulum laoreet posuere neque, sit amet dictum urna fringilla sed. In in ante vitae sapien blandit elementum sit amet ac erat. Nunc semper hendrerit turpis sit amet tempus. Mauris imperdiet mattis feugiat. Ut et erat euismod, finibus enim et, placerat tellus. Mauris laoreet tellus at erat blandit dignissim. Donec id enim at erat imperdiet gravida et eget dui.',},
    {cod: 7,  nome: 'Petit Gateau',                   categoria: 3,   valor: 17.20, imagem: 'Doce_1.jpeg',    visible: false, descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nunc sem, interdum ut consectetur ut, elementum ac turpis. Sed at ullamcorper massa, in fermentum leo. Aliquam erat volutpat. Integer non velit a ante laoreet elementum. Proin aliquet arcu at quam dapibus, nec laoreet ante vehicula. Donec condimentum accumsan molestie. Vestibulum laoreet posuere neque, sit amet dictum urna fringilla sed. In in ante vitae sapien blandit elementum sit amet ac erat. Nunc semper hendrerit turpis sit amet tempus. Mauris imperdiet mattis feugiat. Ut et erat euismod, finibus enim et, placerat tellus. Mauris laoreet tellus at erat blandit dignissim. Donec id enim at erat imperdiet gravida et eget dui.',},
    {cod: 8,  nome: 'Milkshake',                      categoria: 3,   valor: 19.45, imagem: 'Doce_2.jpeg',    visible: false, descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nunc sem, interdum ut consectetur ut, elementum ac turpis. Sed at ullamcorper massa, in fermentum leo. Aliquam erat volutpat. Integer non velit a ante laoreet elementum. Proin aliquet arcu at quam dapibus, nec laoreet ante vehicula. Donec condimentum accumsan molestie. Vestibulum laoreet posuere neque, sit amet dictum urna fringilla sed. In in ante vitae sapien blandit elementum sit amet ac erat. Nunc semper hendrerit turpis sit amet tempus. Mauris imperdiet mattis feugiat. Ut et erat euismod, finibus enim et, placerat tellus. Mauris laoreet tellus at erat blandit dignissim. Donec id enim at erat imperdiet gravida et eget dui.',},
    {cod: 9,  nome: 'Pá Cumê',                        categoria: 3,   valor: 16.00, imagem: 'Doce_3.jpeg',    visible: false, descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nunc sem, interdum ut consectetur ut, elementum ac turpis. Sed at ullamcorper massa, in fermentum leo. Aliquam erat volutpat. Integer non velit a ante laoreet elementum. Proin aliquet arcu at quam dapibus, nec laoreet ante vehicula. Donec condimentum accumsan molestie. Vestibulum laoreet posuere neque, sit amet dictum urna fringilla sed. In in ante vitae sapien blandit elementum sit amet ac erat. Nunc semper hendrerit turpis sit amet tempus. Mauris imperdiet mattis feugiat. Ut et erat euismod, finibus enim et, placerat tellus. Mauris laoreet tellus at erat blandit dignissim. Donec id enim at erat imperdiet gravida et eget dui.',},
    {cod: 10, nome: 'Pudim',                          categoria: 3,   valor: 1.25,  imagem: 'Doce_4.jpeg',    visible: false, descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nunc sem, interdum ut consectetur ut, elementum ac turpis. Sed at ullamcorper massa, in fermentum leo. Aliquam erat volutpat. Integer non velit a ante laoreet elementum. Proin aliquet arcu at quam dapibus, nec laoreet ante vehicula. Donec condimentum accumsan molestie. Vestibulum laoreet posuere neque, sit amet dictum urna fringilla sed. In in ante vitae sapien blandit elementum sit amet ac erat. Nunc semper hendrerit turpis sit amet tempus. Mauris imperdiet mattis feugiat. Ut et erat euismod, finibus enim et, placerat tellus. Mauris laoreet tellus at erat blandit dignissim. Donec id enim at erat imperdiet gravida et eget dui.',},
    {cod: 11, nome: 'Monster with Brothers',          categoria: 4,   valor: 1.20,  imagem: 'Bebida_1.jpeg',  visible: false, descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nunc sem, interdum ut consectetur ut, elementum ac turpis. Sed at ullamcorper massa, in fermentum leo. Aliquam erat volutpat. Integer non velit a ante laoreet elementum. Proin aliquet arcu at quam dapibus, nec laoreet ante vehicula. Donec condimentum accumsan molestie. Vestibulum laoreet posuere neque, sit amet dictum urna fringilla sed. In in ante vitae sapien blandit elementum sit amet ac erat. Nunc semper hendrerit turpis sit amet tempus. Mauris imperdiet mattis feugiat. Ut et erat euismod, finibus enim et, placerat tellus. Mauris laoreet tellus at erat blandit dignissim. Donec id enim at erat imperdiet gravida et eget dui.',},
    {cod: 12, nome: 'Monster with Brothers',          categoria: 4,   valor: 1.20,  imagem: 'Bebida_2.jpeg',  visible: false, descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nunc sem, interdum ut consectetur ut, elementum ac turpis. Sed at ullamcorper massa, in fermentum leo. Aliquam erat volutpat. Integer non velit a ante laoreet elementum. Proin aliquet arcu at quam dapibus, nec laoreet ante vehicula. Donec condimentum accumsan molestie. Vestibulum laoreet posuere neque, sit amet dictum urna fringilla sed. In in ante vitae sapien blandit elementum sit amet ac erat. Nunc semper hendrerit turpis sit amet tempus. Mauris imperdiet mattis feugiat. Ut et erat euismod, finibus enim et, placerat tellus. Mauris laoreet tellus at erat blandit dignissim. Donec id enim at erat imperdiet gravida et eget dui.',},
    {cod: 13, nome: 'Monster with Brothers',          categoria: 4,   valor: 1.20,  imagem: 'Bebida_3.jpeg',  visible: false, descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nunc sem, interdum ut consectetur ut, elementum ac turpis. Sed at ullamcorper massa, in fermentum leo. Aliquam erat volutpat. Integer non velit a ante laoreet elementum. Proin aliquet arcu at quam dapibus, nec laoreet ante vehicula. Donec condimentum accumsan molestie. Vestibulum laoreet posuere neque, sit amet dictum urna fringilla sed. In in ante vitae sapien blandit elementum sit amet ac erat. Nunc semper hendrerit turpis sit amet tempus. Mauris imperdiet mattis feugiat. Ut et erat euismod, finibus enim et, placerat tellus. Mauris laoreet tellus at erat blandit dignissim. Donec id enim at erat imperdiet gravida et eget dui.',},
    {cod: 14, nome: 'Toddy with Brothers',            categoria: 4,   valor: 1.25,  imagem: 'Bebida_4.jpeg',  visible: false, descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nunc sem, interdum ut consectetur ut, elementum ac turpis. Sed at ullamcorper massa, in fermentum leo. Aliquam erat volutpat. Integer non velit a ante laoreet elementum. Proin aliquet arcu at quam dapibus, nec laoreet ante vehicula. Donec condimentum accumsan molestie. Vestibulum laoreet posuere neque, sit amet dictum urna fringilla sed. In in ante vitae sapien blandit elementum sit amet ac erat. Nunc semper hendrerit turpis sit amet tempus. Mauris imperdiet mattis feugiat. Ut et erat euismod, finibus enim et, placerat tellus. Mauris laoreet tellus at erat blandit dignissim. Donec id enim at erat imperdiet gravida et eget dui.',}
  ]

  public selected = 0;

  constructor(private router: Router) {
    // Para começar com alguma categoria selecionada basta utilizar:
    // this.escolhaCardapio();
  }

  ngOnInit() {
  }

  formatacao(valor : any) {
    return valor.toFixed(2).toString().replace(".", ",");
  }

  guiaDetalhes(produto : any) {
    this.router.navigate(['/detalhes', { produto: JSON.stringify(produto) }]);
  }

  escolhaCardapio(categoriaCod : any) {
    this.produtos.map(produto => produto.visible = false);
    this.produtos.filter(produto => produto.categoria == categoriaCod).map(produto => produto.visible = true);
  }

}